---
title: "DD_Code"
author: "Jesse Warren"
date: "10/20/2019"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r}
#To Do
  #Use 2010 Census for Common Support data
  #Only use possession, not sales as these arent legal - Consider this
  #Add decriminilization info
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidycensus)
library(readxl)
library(knitr)
library(broom)
library(foreign)
library(fuzzyjoin)
library(lmtest)
library(multiwayvcov)
library(stargazer)
library(ggrepel)
library(sjPlot)
library(estimatr)

options(scipen=999)
```


```{r load UCR data, cache=TRUE}
#loop to load data
UCR_files <- list.files("Data/UCR", pattern = ".tsv$", recursive = TRUE)
UCR_files <- UCR_files[-which(str_detect(UCR_files, "UCR_2015"))] #remove 2015, because it doesnt have yearly summarized data, and needs to be dealt with separately
UCR_data_list <- vector("list", length(UCR_files))
UCR_data_names <- stringr::str_sub(UCR_files, 1, 8)
names(UCR_data_list) <- UCR_data_names

for (i in seq_along(UCR_files)){
  UCR_data_list[[UCR_data_names[i]]] <- read_tsv(paste0("Data/UCR/", UCR_files[i]))
}

#check that colnames are the same
colnames(UCR_data_list[[1]]) == colnames(UCR_data_list[[2]])


#load 2015 separately because there is no yearly summarized data, just data broken down by month
UCR_2015 <- read_tsv("Data/UCR/UCR_2015/DS0001/36794-0001-Data.tsv")

#replace all 99999, 99998 values, which code as missing, with 0s
UCR_2015[UCR_2015 == 99999] <- 0
UCR_2015[UCR_2015 == 99998] <- 0
UCR_2015[is.na(UCR_2015)] <- 0



#adjust UCR 2015 offense codes to match other years
UCR_2015$OFFENSE[UCR_2015$OFFENSE == "18F"] <-  "187"
UCR_2015$OFFENSE[UCR_2015$OFFENSE == "18B"] <-  "182"
UCR_2015$OFFENSE[UCR_2015$OFFENSE == "14"] <-  "140"
UCR_2015$OFFENSE[UCR_2015$OFFENSE == "22"] <-  "220"
UCR_2015$OFFENSE[UCR_2015$OFFENSE == "23"] <-  "230"
UCR_2015$OFFENSE[UCR_2015$OFFENSE == "24"] <-  "240"
UCR_2015$OFFENSE[UCR_2015$OFFENSE == "25"] <-  "250"
UCR_2015$OFFENSE[UCR_2015$OFFENSE == "27"] <-  "270"
UCR_2015$OFFENSE[UCR_2015$OFFENSE == "28"] <-  "280"
UCR_2015$OFFENSE[UCR_2015$OFFENSE == "01A"] <-  "011"
UCR_2015$OFFENSE[UCR_2015$OFFENSE == "01B"] <-  "012"
UCR_2015$OFFENSE[UCR_2015$OFFENSE == "02"] <-  "020"
UCR_2015$OFFENSE[UCR_2015$OFFENSE == "03"] <-  "030"
UCR_2015$OFFENSE[UCR_2015$OFFENSE == "04"] <-  "040"
UCR_2015$OFFENSE[UCR_2015$OFFENSE == "05"] <-  "050"
UCR_2015$OFFENSE[UCR_2015$OFFENSE == "06"] <-  "060"
UCR_2015$OFFENSE[UCR_2015$OFFENSE == "07"] <-  "070"
UCR_2015$OFFENSE[UCR_2015$OFFENSE == "08"] <-  "080"
UCR_2015$OFFENSE[UCR_2015$OFFENSE == "09"] <-  "090"


#get 2015 yearly summary, but only include larger agencies
agency_population_to_filter_by <- 200000

UCR_data_list$UCR_2015 <- UCR_2015 %>%
  dplyr::select(STATE, STNAME, COUNTY, AGENCY, GROUP, OFFENSE, POP, 34:89) %>% 
  filter(POP > agency_population_to_filter_by) %>% 
  group_by(STATE, STNAME, COUNTY, AGENCY, OFFENSE, GROUP, POP) %>%
  summarise_each(funs(sum))

```

```{r load ACS city population data, cache=TRUE}

#load variable list
vlist1 <- load_variables(2016, "acs5", cache = TRUE)
vlist2 <- load_variables(2009, "acs5", cache = TRUE)



#load ACS city population data
pop_ACS_years <- lst(2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016)

ACS_city_pops <- map_dfr(
  pop_ACS_years, 
  ~ get_acs(geography = "place", variables = c(total_pop = "B03002_001",
                                               white_pop = "B03002_003",
                                               black_pop = "B03002_004",
                                               unweighted_sample_count_of_pop = "B00001_001"),
            year = .x, output = "wide"),
  .id = "year") %>% 
  dplyr::select(-total_popM) %>% 
  arrange(year, GEOID)


#info on UCR population tallies - NOT NEEDED https://www.ucrdatatool.gov/faq.cfm

# UCR_data_list$UCR_2011 %>%
#   filter(GROUP == "1A" | GROUP == "1B" | GROUP == "1C") %>%
#   filter(OFFENSE == "187") %>%
#   arrange(desc(POP))
# 
# ACS_city_pops %>%
#   filter(year == 2011) %>%
#   arrange(desc(total_popE))


#add state variable to city population data
ACS_city_name_extraction_function <- function(df){
  df <- df %>% 
  mutate(State = str_extract(NAME, '\\b[^,]+$')) 

df <- df %>% 
  mutate(City = str_extract(NAME, '^[^,]*')) %>% #remove commas
  mutate(City = str_remove(City, "city")) %>% #remove city
  mutate(City = str_remove(City, "municipality")) %>% #remove  "municipality"
  mutate(City = str_remove(City, "metro")) %>% #remove  "metro"
  mutate(City = trimws(City, "right")) %>%  #remove trailing whitespace
  rename(ACS_city_name = City)
}

ACS_city_pops <- ACS_city_pops %>% 
  mutate(State = str_extract(NAME, '\\b[^,]+$')) 

ACS_city_pops <- ACS_city_pops %>% 
  mutate(City = str_extract(NAME, '^[^,]*')) %>% #remove commas
  mutate(City = str_remove(City, "city")) %>% #remove city
  mutate(City = str_remove(City, "municipality")) %>% #remove  "municipality"
  mutate(City = str_remove(City, "metro")) %>% #remove  "metro"
  mutate(City = trimws(City, "right")) %>%  #remove trailing whitespace
  rename(ACS_city_name = City)

#remove smaller cities to make df easier to work with
ACS_city_pops <- ACS_city_pops %>% 
  filter(total_popE > 150000)

```


```{r calculate citywide arrest totals and rates for all years and loop into list, cache=TRUE}

#race categories
  # AW = Adult White
  # AB = Adult Black
  # AI = Adult Indian
  # AA = Adult Asian
  # JW = Juvenile White
  # JB = Juvenile Black
  # JI = Juvenile Indian
  # JA = Juvenile Asian
#ethnicity categories
  # AH = Adult Hispanic
  # AN = Adult Non-Hispanic
  # JH = Juvenile Hispanic
  # JN = Juvenile Non-Hispanic


#remove all small population areas to speed up processing
for(i in 1:length(UCR_data_list)){
  UCR_data_list[[i]] <- UCR_data_list[[i]] %>% 
    filter(POP > agency_population_to_filter_by)
}

#get list of cities to include, all of which must have had populations over 250,000 in 2010
sample_cities_df <- vector("list", length(UCR_data_list))
names(sample_cities_df) <- names(UCR_data_list)

for(i in 1:length(UCR_data_list)){
  sample_cities_df[[i]] <- UCR_data_list[[i]] %>% 
    ungroup() %>% 
    dplyr::select(AGENCY, POP, GROUP) %>%
    unique()
}

inital_year_column_label <- names(UCR_data_list)[1]


sample_cities_df <- bind_rows(sample_cities_df, .id = "column_label") %>%
  arrange(column_label) %>% 
  filter(column_label == inital_year_column_label) %>% 
  filter(GROUP == "1A" | GROUP == "1B" | GROUP == "1C")

sample_cities_vec <- sample_cities_df %>%
  pull(AGENCY)


#city arrest totals and rates list
UCR_arrest_totals_and_rates <- vector("list", length(UCR_data_list))
names(UCR_arrest_totals_and_rates) <- names(UCR_data_list)

#progress bar
p <- progress_estimated(length(UCR_data_list))


#loop over all
for(i in 1:length(UCR_data_list)){
  p$tick()$print()
  #replace all 99999, 99998 values, which code as missing, with 0s
  UCR_data_list[[i]][UCR_data_list[[i]] == 999999] <- 0
  UCR_data_list[[i]][UCR_data_list[[i]] == 999998] <- 0
  UCR_data_list[[i]][is.na(UCR_data_list[[i]])] <- 0
  

  
  #calculate % of total arrests that are african american, white
  UCR_arrest_totals_and_rates[[i]] <- UCR_data_list[[i]] %>% 
    filter(AGENCY %in% sample_cities_vec) %>% 
    group_by(STNAME, AGENCY, POP, GROUP) %>% 
    filter(OFFENSE != "998", OFFENSE != "000") %>% 
    summarize(total_arrests_race_data = (sum(AW) + sum(AB) + sum(AI) + sum(AA) + sum(JW) + sum(JB) + sum(JI) + sum(JA)),
              total_White_arrests = (sum(AW) + sum(JW)),
              total_African_American_arrests = (sum(AB) + sum(JB))) %>%
    arrange(STNAME, AGENCY)
    
  #calculate total violent arrests
  UCR_arrest_totals_and_rates[[i]] <- full_join(UCR_arrest_totals_and_rates[[i]],
    UCR_data_list[[i]] %>% 
      filter(AGENCY %in% sample_cities_vec) %>% 
      group_by(STNAME, AGENCY, POP, GROUP) %>% 
      filter(OFFENSE == "011" | OFFENSE == "012" | OFFENSE == "020" | OFFENSE == "030" | OFFENSE == "040" | OFFENSE == "050" | OFFENSE == "060" | OFFENSE == "070" | OFFENSE == "080" | OFFENSE == "090") %>% 
      summarize(total_violent_arrests = (sum(AW) + sum(AB) + sum(AI) + sum(AA) + sum(JW) + sum(JB) + sum(JI) + sum(JA))) %>%
      arrange(STNAME, AGENCY), 
    by = c("STNAME", "AGENCY", "POP", "GROUP"))
  
  #calculate % of marijuana possession arrests that are african american, white
  UCR_arrest_totals_and_rates[[i]] <- full_join(UCR_arrest_totals_and_rates[[i]],
    UCR_data_list[[i]] %>% 
      filter(AGENCY %in% sample_cities_vec) %>% 
      group_by(STNAME, AGENCY, POP, GROUP) %>% 
      filter(OFFENSE == "187") %>%  #only include marijuana possession (187)
      summarize(total_marijuana_possession_arrests_race_data = (sum(AW) + sum(AB) + sum(AI) + sum(AA) + sum(JW) + sum(JB) + sum(JI) + sum(JA)),
                total_White_marijuana_possession_arrests = (sum(AW) + sum(JW)),
                total_African_American_marijuana_possession_arrests = (sum(AB) + sum(JB))) %>% 
      arrange(STNAME, AGENCY), 
    by = c("STNAME", "AGENCY", "POP", "GROUP"))
  
    #calculate % of marijuana possession and sale arrests that are african american, white
  UCR_arrest_totals_and_rates[[i]] <- full_join(UCR_arrest_totals_and_rates[[i]],
    UCR_data_list[[i]] %>% 
      filter(AGENCY %in% sample_cities_vec) %>% 
      group_by(STNAME, AGENCY, POP, GROUP) %>% 
      filter(OFFENSE == "187" | OFFENSE == "182") %>%  #only include marijuana possession (187) or marijuana sale (182)
      summarize(total_marijuana_possession_and_sale_arrests_race_data = (sum(AW) + sum(AB) + sum(AI) + sum(AA) + sum(JW) + sum(JB) + sum(JI) + sum(JA)),
                total_White_marijuana_possession_and_sale_arrests = (sum(AW) + sum(JW)),
                total_African_American_marijuana_possession_and_sale_arrests = (sum(AB) + sum(JB))) %>% 
      arrange(STNAME, AGENCY), 
    by = c("STNAME", "AGENCY", "POP", "GROUP"))
  
  #calculate % of non-violent, non-drug related misdemeanor arrests that are african american, white. These include:
    #140 = Vandalism
    #220 = Liquor Laws
    #230 = Drunkennes
    #240 = Disorderly Conduct
    #250 = Vagrancy
    #270 = Suspicion
    #280 = Curfew and loitering violations
  UCR_arrest_totals_and_rates[[i]] <- full_join(UCR_arrest_totals_and_rates[[i]],
    UCR_data_list[[i]] %>% 
      filter(AGENCY %in% sample_cities_vec) %>% 
      group_by(STNAME, AGENCY, POP, GROUP) %>% 
      filter(OFFENSE == "140" | OFFENSE == "220" | OFFENSE == "230" | OFFENSE == "240" | OFFENSE == "250" | OFFENSE == "270" | OFFENSE == "280") %>%
      summarize(total_non_violent_non_drug_misdemeanor_arrests_race_data = (sum(AW) + sum(AB) + sum(AI) + sum(AA) + sum(JW) + sum(JB) + sum(JI) + sum(JA)),
                total_White_non_drug_misdemeanor_arrests = (sum(AW) + sum(JW)),
                total_African_American_non_drug_misdemeanor_arrests = (sum(AB) + sum(JB))) %>% 
      arrange(STNAME, AGENCY), 
    by = c("STNAME", "AGENCY", "POP", "GROUP"))
  
  
}  

#bind into one df
UCR_arrest_totals_and_rates <- bind_rows(UCR_arrest_totals_and_rates, .id = "column_label") %>% 
  arrange(column_label)

#remove MSA County and non MSA County observations to just get city agencies
UCR_arrest_totals_and_rates <- UCR_arrest_totals_and_rates %>% 
  filter(GROUP != "2") %>% 
  filter(GROUP != "9A")

#check there are observations for each year for each agency
number_of_observation_years <- length(names(UCR_data_list))

UCR_arrest_totals_and_rates %>% 
  group_by(AGENCY) %>% 
  summarise(count = n()) %>% 
  filter(count < number_of_observation_years)

#get list of agencies with missing years of data, exclude these from sample
agencies_with_missing_years <- UCR_arrest_totals_and_rates %>% 
  group_by(AGENCY) %>% 
  summarise(count = n()) %>% 
  filter(count < number_of_observation_years) %>% 
  pull(AGENCY)

UCR_arrest_totals_and_rates <- UCR_arrest_totals_and_rates %>% 
  filter(!AGENCY %in% agencies_with_missing_years)

#update sample cities vector to not include agencies with 1 or more year of missing data
sample_cities_vec <- as.data.frame(sample_cities_vec) %>% 
  filter(!sample_cities_vec %in% agencies_with_missing_years) %>% 
  pull(sample_cities_vec) %>% 
  as.character()

#save to csv if needed later
write_csv(UCR_arrest_totals_and_rates, "Calculated_UCR_Citywide_Data.csv")
```



```{r Load UCR county codes}
# #Load UCR Crosswalk with UCR to FIPS County and State Codes
# UCR_crosswalk <- read_tsv("Data/UCR_State_County_Codes/UCR_Crosswalk/DS0001/35158-0001-Data.tsv") %>% 
#   dplyr::select(FIPS_ST, FIPS_COUNTY, U_STATENO, U_CNTY)
# 
# #merge with UCR data
# UCR_arrest_totals_and_rates <- UCR_arrest_totals_and_rates %>% 
#   left_join(UCR_crosswalk, by = c("STATE" = "U_STATENO", "COUNTY" = "U_CNTY"))
# 
# #remove NA columns that we can't place with County crosswalk data
# UCR_arrest_totals_and_rates <- UCR_arrest_totals_and_rates %>% 
#   filter(!is.na(FIPS_COUNTY))

```


```{r Combine city pop and arrest data}
#create year column
UCR_arrest_totals_and_rates <- UCR_arrest_totals_and_rates %>% 
  mutate(year = str_sub(column_label, start = -4)) %>% 
  dplyr::select(-column_label)

#load sheet with matched names
state_name_matching_key <- read_excel("State_Name_Matching.xlsx")
UCR_arrest_totals_and_rates <- full_join(UCR_arrest_totals_and_rates, state_name_matching_key, by = "STNAME") %>% 
  rename(State = NAME)

#format UCR data to facilitate matching with ACS city pop data
UCR_arrest_totals_and_rates <- UCR_arrest_totals_and_rates %>% 
  mutate(City = str_to_sentence(AGENCY))

#remove NA rows in UCR_arrest_totals_and_rates
UCR_arrest_totals_and_rates <- na.omit(UCR_arrest_totals_and_rates)


#get just column of ACS city names to match on
ACS_city_pops_names <- ACS_city_pops %>% 
  select(ACS_city_name) %>% 
  unique()

#fuzzy match to add ACS_city_names
UCR_arrest_totals_and_rates <- UCR_arrest_totals_and_rates %>% 
  stringdist_left_join(ACS_city_pops_names, by = c("City" = "ACS_city_name"), max_dist = 1, distance_col = "fuzzy_distance") 

#join with ACS city population data
UCR_arrest_totals_and_rates <- UCR_arrest_totals_and_rates %>% 
  left_join(ACS_city_pops, by = c("year", "State", "ACS_city_name")) %>% 
  mutate(UCR_to_ACS_pop_ratio = POP / total_popE)

#filter out cities with no matched names from ACS data - Louisville, Charlotte, Las Vegas, Indianapolis
UCR_arrest_totals_and_rates <- UCR_arrest_totals_and_rates %>% 
  filter(!is.na(ACS_city_name))

#rearrange column order, drop unnecessary columns
UCR_arrest_totals_and_rates_with_pop <- UCR_arrest_totals_and_rates %>% 
  ungroup() %>% 
  dplyr::select(-STNAME) %>% 
  dplyr::select(year, State, City, ACS_city_name, AGENCY, GROUP, GEOID, UCR_pop = POP, total_popE, white_popE, white_popM, black_popE, black_popM, unweighted_sample_count_of_popE, UCR_to_ACS_pop_ratio, 4:17)

#update list of all cities in sample to have ACS city name
sample_cities_vec <- UCR_arrest_totals_and_rates_with_pop %>% 
  select(ACS_city_name) %>% 
  unique() %>% 
  arrange(ACS_city_name) %>% 
  pull(ACS_city_name)
```

```{r add legalization status}

#load legalization status spreadsheets
legalization_status_one_equals_any_legalization_in_year <- read_excel("Marijuana_Legalization_Status_One_Equals_Any_Legalization_In_Year.xlsx") %>% 
  gather(year, legalization_status_one_equals_any_legalization_in_year, -State)

legalization_status_one_equals_legalization_entire_year <- read_excel("Marijuana_Legalization_Status_One_Equals_Legalization_Entire_Year.xlsx") %>% 
  gather(year, legalization_status_one_equals_entire_year, -State)

legalization_status_fraction_of_year_legalized <- read_excel("Marijuana_Legalization_Status_Fraction_Of_Year_Legalized.xlsx") %>% 
  gather(year, legalization_status_fraction_of_year_legalized, -State)

UCR_arrest_totals_and_rates_with_pop <- UCR_arrest_totals_and_rates_with_pop %>% 
  left_join(legalization_status_one_equals_any_legalization_in_year, by = c("State", "year")) %>% 
  left_join(legalization_status_one_equals_legalization_entire_year, by = c("State", "year")) %>% 
  left_join(legalization_status_fraction_of_year_legalized, by = c("State", "year"))


#load decriminilization status spreadsheets
decriminilization_status_one_equals_any_legalization_in_year <- read_excel("Marijuana_Decriminilization_Status_One_Equals_Any_Legalization_In_Year.xlsx") %>% 
  gather(year, decriminilization_status_one_equals_any_legalization_in_year, -State)

decriminilization_status_one_equals_legalization_entire_year <- read_excel("Marijuana_Decriminilization_Status_One_Equals_Legalization_Entire_Year.xlsx") %>% 
  gather(year, decriminilization_status_one_equals_entire_year, -State)

decriminilization_status_fraction_of_year_legalized <- read_excel("Marijuana_Decriminilization_Status_Fraction_Of_Year_Legalized.xlsx") %>% 
  gather(year, decriminilization_status_fraction_of_year_legalized, -State)

decriminilization_status_fraction_of_year_legalized_by_city <- 
  read_excel("Marijuana_Decriminilization_Status_Fraction_Of_Year_Legalized_by_city.xlsx") %>% 
  gather(year, decriminilization_status_fraction_of_year_legalized_by_city, -State, -ACS_city_name)

decriminilization_status_one_equals_any_legalization_in_year_by_city <- 
  read_excel("Marijuana_Decriminilization_Status_One_Equals_Any_Legalization_by_city.xlsx") %>% 
  gather(year, decriminilization_status_one_equals_any_legalization_in_year_by_city, -State, -ACS_city_name)


UCR_arrest_totals_and_rates_with_pop <- UCR_arrest_totals_and_rates_with_pop %>% 
  left_join(decriminilization_status_one_equals_any_legalization_in_year, by = c("State", "year")) %>% 
  left_join(decriminilization_status_one_equals_legalization_entire_year, by = c("State", "year")) %>% 
  left_join(decriminilization_status_fraction_of_year_legalized, by = c("State", "year")) %>% 
  left_join(decriminilization_status_fraction_of_year_legalized_by_city, by = c("State", "ACS_city_name", "year")) %>% 
  left_join(decriminilization_status_one_equals_any_legalization_in_year_by_city, by = c("State", "ACS_city_name", "year"))



#create vector of states that legalized by end of 2016
states_that_decriminalized_by_end_of_2016_vector <- UCR_arrest_totals_and_rates_with_pop %>% 
  filter(year == 2016) %>% 
  filter(decriminilization_status_fraction_of_year_legalized > 0) %>% 
  select(State) %>% 
  unique() %>%
  arrange(State) %>% 
  pull(State)

#create vector of cities that legalized by end of 2016
cities_that_decriminalized_by_end_of_2016_vector <- UCR_arrest_totals_and_rates_with_pop %>% 
  filter(year == 2016) %>% 
  filter(decriminilization_status_fraction_of_year_legalized_by_city > 0) %>% 
  select(City) %>% 
  unique() %>% 
  arrange(City) %>% 
  pull(City)

```

```{r convert columns to correct types and rename}
UCR_arrest_totals_and_rates_with_pop <- UCR_arrest_totals_and_rates_with_pop %>% 
  rename(Year = year) %>% 
  mutate(State = as.factor(State),
         Year = as.factor(Year),
         GEOID = as.factor(GEOID),
         City = as.factor(City))

```

```{r calculate arrest rates per 1000 people for each race}
UCR_arrest_totals_and_rates_with_pop <- UCR_arrest_totals_and_rates_with_pop %>% 
  mutate(total_arrest_rate = (total_arrests_race_data / total_popE)*1000) %>% 
  mutate(total_violent_arrest_rate = (total_violent_arrests / total_popE)*1000) %>% 
  mutate(marijuana_possession_arrest_rate = (total_marijuana_possession_arrests_race_data / total_popE)*1000) %>% 
  mutate(marijuana_possession_and_sale_arrest_rate = (total_marijuana_possession_and_sale_arrests_race_data / total_popE)*1000) %>% 
  mutate(white_arrest_rate = (total_White_arrests / white_popE)*1000) %>% 
  mutate(black_arrest_rate = (total_African_American_arrests / black_popE)*1000) %>% 
  mutate(white_marijuana_possession_arrest_rate = (total_White_marijuana_possession_arrests / white_popE)*1000) %>% 
  mutate(black_marijuana_possession_arrest_rate = (total_African_American_marijuana_possession_arrests / black_popE)*1000) %>% 
  mutate(white_marijuana_possession_and_sale_arrest_rate = (total_White_marijuana_possession_and_sale_arrests / white_popE)*1000) %>% 
  mutate(black_marijuana_possession_and_sale_arrest_rate = (total_African_American_marijuana_possession_and_sale_arrests / black_popE)*1000) %>% 
  mutate(non_drug_misdemeanor_arrest_rate = (total_non_violent_non_drug_misdemeanor_arrests_race_data / total_popE)*1000) %>% 
  mutate(white_non_drug_misdemeanor_arrest_rate = (total_White_non_drug_misdemeanor_arrests / white_popE)*1000) %>% 
  mutate(black_non_drug_misdemeanor_arrest_rate = (total_African_American_non_drug_misdemeanor_arrests / black_popE)*1000)


#calculate arrest rate disparity ratios - 1 indicates same arrest rate. higher than 1 indicates higher black arrest rate, lower than 1 indicates higher white arrest rate
UCR_arrest_totals_and_rates_with_pop <- UCR_arrest_totals_and_rates_with_pop %>% 
  mutate(total_arrest_rate_disparity = black_arrest_rate / white_arrest_rate,
         marijuana_possession_arrest_rate_disparity = black_marijuana_possession_arrest_rate / white_marijuana_possession_arrest_rate,
         marijuana_possession_and_sale_arrest_rate_disparity = black_marijuana_possession_and_sale_arrest_rate / white_marijuana_possession_and_sale_arrest_rate,
         non_drug_misdemeanor_arrest_rate_disparity = black_non_drug_misdemeanor_arrest_rate / white_non_drug_misdemeanor_arrest_rate)


```

```{r remove states that don't report to UCR}
#certain states dont report to UCR or underreport significantly. Remove these states
states_that_dont_report_to_UCR_or_underreport <- c("Illinois", "Florida", "District of Columbia", "New York")

UCR_arrest_totals_and_rates_with_pop <- UCR_arrest_totals_and_rates_with_pop %>% 
  filter(!State %in% states_that_dont_report_to_UCR_or_underreport)

```


```{r Load common support ACS data}
#select common support regression year
common_support_regression_year <- 2009

common_support_vlist0 <- load_variables(common_support_regression_year, "acs5", cache = TRUE)


#load 2009 ACS data for common support regression
ACS_common_support_data <- get_acs(geography = "place", variables = c(total_pop = "B03002_001",
                                               total_pop_poverty_status = "B17001_001",
                                               income_below_poverty_level_last_12_months = "B17001_002",
                                               total_pop_education = "B23006_001",
                                               high_school_grad = "B23006_009",
                                               some_college_or_associates = "B23006_016",
                                               bachelors_or_higher = "B23006_023",
                                               total_pop_citizenship = "B05001_001",
                                               not_US_citizen = "B05001_006"),
            year = common_support_regression_year)

# get from decennial census - not used currently
# ACS_common_support_data <- get_decennial(geography = "place", variables = c(total_pop = "B03002_001", 
#                                                total_pop_poverty_status = "B17001_001",
#                                                income_below_poverty_level_last_12_months = "B17001_002",
#                                                total_pop_education = "B23006_001",
#                                                high_school_grad_or_higher = "B23006_009",
#                                                some_college_or_associates = "B23006_016",
#                                                bachelors_or_higher = "B23006_023",
#                                                total_pop_citizenship = "B05001_001",
#                                                not_US_citizen = "B05001_006"),
#             year = common_support_regression_year)

#calculate summary statistics for common support regression
ACS_common_support_data <- ACS_common_support_data %>% 
  dplyr::select(-moe) %>% 
  spread(variable, estimate) %>% 
  mutate(log_total_pop = log(total_pop),
    pct_in_poverty = income_below_poverty_level_last_12_months / total_pop_poverty_status,
    pct_high_school_diploma_or_higher = (high_school_grad + some_college_or_associates + bachelors_or_higher) / total_pop_education,
        pct_not_US_citizen = not_US_citizen / total_pop_citizenship) %>% 
  filter(NAME != "Puerto Rico") %>% 
  dplyr::select(GEOID, NAME, log_total_pop, total_pop, pct_in_poverty, pct_high_school_diploma_or_higher, pct_not_US_citizen)

ACS_common_support_data <- ACS_city_name_extraction_function(ACS_common_support_data)

#remove smaller cities to make df easier to work with
ACS_common_support_data <- ACS_common_support_data %>% 
  filter(total_pop > 150000)

#merge with marijuana legalization and decriminilization data
ACS_common_support_data <- legalization_status_one_equals_any_legalization_in_year %>% 
  filter(year == 2016) %>% 
  left_join(ACS_common_support_data,  by = "State") %>% 
  rename(legalized_by_end_of_2016 = legalization_status_one_equals_any_legalization_in_year) %>% 
  dplyr::select(-year)

ACS_common_support_data <- decriminilization_status_one_equals_any_legalization_in_year %>% 
  filter(year == 2016) %>% 
  left_join(ACS_common_support_data,  by = "State") %>% 
  rename(state_decriminalized_by_end_of_2016 = decriminilization_status_one_equals_any_legalization_in_year) %>% 
  dplyr::select(-year)

ACS_common_support_data <- decriminilization_status_fraction_of_year_legalized_by_city %>% 
  filter(year == 2016) %>% 
  left_join(ACS_common_support_data,  by = c("State", "ACS_city_name")) %>% 
  rename(city_decriminalized_by_end_of_2016 = decriminilization_status_fraction_of_year_legalized_by_city) %>% 
  dplyr::select(-year)



#remove NAs for states with no cities
ACS_common_support_data <- ACS_common_support_data %>% 
  filter(!is.na(GEOID))



#run Common Support regression
common_support_regression <- lm(city_decriminalized_by_end_of_2016 ~ log_total_pop +
                                                           pct_high_school_diploma_or_higher +
                                                           pct_not_US_citizen +
                                                           pct_in_poverty,
                                data = ACS_common_support_data)
summary(common_support_regression)

#add column with common support regression prediction results
ACS_common_support_data <- cbind(ACS_common_support_data, as.data.frame(predict.lm(common_support_regression))) %>%
  rename(probability_of_decriminilization_log_odds = `predict.lm(common_support_regression)`) %>% 
  mutate(probability_of_decriminilization = plogis(probability_of_decriminilization_log_odds))


#select common support cities
max_probability_of_non_decriminalized_city <- max(ACS_common_support_data$probability_of_decriminilization[ACS_common_support_data$city_decriminalized_by_end_of_2016 == 0])   
min_probability_of_decriminalized_city <- min(ACS_common_support_data$probability_of_decriminilization[ACS_common_support_data$city_decriminalized_by_end_of_2016 == 1])

common_support_cities <- ACS_common_support_data %>% 
  filter(probability_of_decriminilization >= min_probability_of_decriminalized_city & probability_of_decriminilization <= max_probability_of_non_decriminalized_city) %>% 
  filter(!State %in% states_that_dont_report_to_UCR_or_underreport) %>% 
  filter(ACS_city_name %in% sample_cities_vec) %>% 
  pull(ACS_city_name)

all_cities <- ACS_common_support_data %>% 
  filter(!State %in% states_that_dont_report_to_UCR_or_underreport) %>% 
  filter(ACS_city_name %in% sample_cities_vec) %>% 
  pull(ACS_city_name)

#get count of common support cities that decriminalized (1), didnt decriminalize (0) that will be used in regressions
ACS_common_support_data %>% 
  filter(ACS_city_name %in% common_support_cities) %>% 
  group_by(legalized_by_end_of_2016) %>% 
  summarize(count = n())

#common support city summary stats
ACS_common_support_data %>% 
  filter(ACS_city_name %in% common_support_cities) %>% 
  summarize(mean_pop = mean(total_pop),
            mean_poverty_rate = mean(pct_in_poverty))



common_support_cities %>% 
  as.data.frame() %>% 
  filter(. %in% sample_cities_vec)
```

```{r Load city control variable data from ACS}
#select years to load controls data for
controls_years <- lst(2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016)

controls_vlist09 <- load_variables(2009, "acs5", cache = TRUE)
controls_vlist10 <- load_variables(2010, "acs5", cache = TRUE)


#load ACS controls data
ACS_control_data <- map_dfr(
  controls_years, 
  ~ get_acs(geography = "place", variables  = c(total_pop = "B03002_001",
                                               black_pop = "B03002_004",
                                               #total_pop_employment = "B23025_001",
                                               #in_labor_force = "B23025_002",
                                               #not_in_labor_force = "B23025_007",
                                               #total_pop_education = "B23006_001",
                                               #high_school_grad_or_higher = "B23006_009",
                                               total_pop_poverty_status = "B17001_001",
                                               income_below_poverty_level_last_12_months = "B17001_002"),
            year = .x, output = "wide"),
  .id = "year") %>% 
  dplyr::select(-ends_with("M")) %>% 
  arrange(year, GEOID)

ACS_control_data <- ACS_city_name_extraction_function(ACS_control_data)


#calculate percentage statistics for controls
ACS_control_data <- ACS_control_data %>% 
  mutate(log_total_pop = log(total_popE),
    pct_black = black_popE / total_popE,
         #pct_high_school_diploma_or_higher = high_school_grad_or_higherE / total_pop_educationE,
         pct_in_poverty = income_below_poverty_level_last_12_monthsE / total_pop_poverty_statusE) %>% 
  filter(!NAME == "Puerto Rico") %>% 
  dplyr::select(NAME, State, ACS_city_name, year, log_total_pop, pct_black, pct_in_poverty)

#merge with UCR data
UCR_arrest_totals_and_rates_with_pop <- UCR_arrest_totals_and_rates_with_pop %>% 
  left_join(ACS_control_data, by = c("State", "ACS_city_name", "Year" = "year"))
```


```{r conduct difference in differences}

#create function for running regressions, with clustering at state level
regression_function_clustered <- function(dependent_variable, common_support, decriminilization) {
  df <- UCR_arrest_totals_and_rates_with_pop %>% 
    filter(ACS_city_name %in% common_support)  %>% 
    filter(pct_black > 0.02)
  outcome <- dependent_variable
  controls <- c(decriminilization, "factor(City)", "factor(Year)", "total_violent_arrest_rate",  "log_total_pop", "pct_black", "pct_in_poverty")
  f <- as.formula(
    paste(outcome, 
          paste(controls, collapse = " + "), 
          sep = " ~ "))
  model <- eval(bquote(lm(.(f), weights = unweighted_sample_count_of_popE, data = df)))
  
  vcov_state <- cluster.vcov(model, ~ State)
  model <- coeftest(model, vcov_state)
  
  print(model)
}


regression_function_no_cluster <- function(dependent_variable, common_support, decriminilization) {
  df <- UCR_arrest_totals_and_rates_with_pop %>% 
    filter(ACS_city_name %in% common_support) %>% 
    filter(pct_black > 0.02)
  outcome <- dependent_variable
  controls <- c(decriminilization, "factor(City)", "factor(Year)", "total_violent_arrest_rate", "log_total_pop", "pct_black", "pct_in_poverty")
  f <- as.formula(
    paste(outcome, 
          paste(controls, collapse = " + "), 
          sep = " ~ "))
  model <- eval(bquote(lm(.(f), weights = unweighted_sample_count_of_popE, data = df)))
  
  summary(model) %>% 
    print()
}



#example regression
UCR_arrest_totals_and_rates_with_pop %>% 
  filter(ACS_city_name %in% common_support_cities) %>% 
  filter(pct_black > 0.05) %>% 
  lm(marijuana_possession_arrest_rate ~ decriminilization_status_fraction_of_year_legalized_by_city +
       factor(City) +
       factor(Year) +
       pct_black +
       pct_in_poverty,
     weights = unweighted_sample_count_of_popE,
     data = .) %>% 
  summary() %>% 
  print() 





sink("regression_results.txt")
#marijuana possession arrest rate, run on just common support cities
print("Marijuana possession arrest rate, just on common support cities")
#regression_function_no_cluster("marijuana_possession_arrest_rate", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")
regression_function_clustered("marijuana_possession_arrest_rate", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")

#marijuana possession and sale arrest rate, run on just common support cities
print("Marijuana possession and sale arrest rate, just on common support cities")
#regression_function_no_cluster("marijuana_possession_and_sale_arrest_rate", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")
regression_function_clustered("marijuana_possession_and_sale_arrest_rate", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")



#marijuana possession arrest rate disparity, run on just common support cities
print("Marijuana possession arrest rate disparity, just on common support cities")
#regression_function_no_cluster("marijuana_possession_arrest_rate_disparity", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")
regression_function_clustered("marijuana_possession_arrest_rate_disparity", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")

#marijuana possession and sale arrest rate disparity, run on just common support cities
print("Marijuana possession and sale arrest rate disparity, just on common support cities")
#regression_function_no_cluster("marijuana_possession_and_sale_arrest_rate_disparity", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")
regression_function_clustered("marijuana_possession_and_sale_arrest_rate_disparity", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")




#black marijuana posession arrest rate, run on just common support cities
print("Black marijuana posession arrest rate, run on just common support cities")
#regression_function_no_cluster("black_marijuana_possession_arrest_rate", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")
regression_function_clustered("black_marijuana_possession_arrest_rate", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")

#black marijuana posession and sale arrest rate, run on just common support cities
print("Black marijuana posession and sale arrest rate, run on just common support cities")
#regression_function_no_cluster("black_marijuana_possession_and_sale_arrest_rate", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")
regression_function_clustered("black_marijuana_possession_and_sale_arrest_rate", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")




#nondrug misdemeanor arrest rate, run on just common support cities
print("Nondrug misdemeanor arrest rate, run on just common support cities")
#regression_function_no_cluster("non_drug_misdemeanor_arrest_rate", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")
regression_function_clustered("non_drug_misdemeanor_arrest_rate", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")





#black nondrug  misdemeanor arrest rate, run on just common support cities
print("Black nondrug  misdemeanor arrest rate, run on just common support cities")
#regression_function_no_cluster("black_non_drug_misdemeanor_arrest_rate", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")
regression_function_clustered("black_non_drug_misdemeanor_arrest_rate", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")



#nondrug misdemeanor arrest rate disparity, run on just common support cities
print("Nondrug misdemeanor arrest rate disparity, run on just common support cities")
#regression_function_no_cluster("non_drug_misdemeanor_arrest_rate_disparity", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")
regression_function_clustered("non_drug_misdemeanor_arrest_rate_disparity", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")


#total arrest rate, run on just common support cities
print("Total arrest rate, run on just common support cities")
#regression_function_no_cluster("total_arrest_rate", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")
regression_function_clustered("total_arrest_rate", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")


#total arrest rate disparity, run on just common support cities
print("Total arrest rate disparity, run on just common support cities")
#regression_function_no_cluster("total_arrest_rate_disparity", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")
regression_function_clustered("total_arrest_rate_disparity", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")


### now use all cities


#marijuana possession arrest rate, run on all cities
print("Marijuana possession arrest rate, all cities")
#regression_function_no_cluster("marijuana_possession_arrest_rate", all_cities, "decriminilization_status_fraction_of_year_legalized_by_city")
regression_function_clustered("marijuana_possession_arrest_rate", all_cities, "decriminilization_status_fraction_of_year_legalized_by_city")

#marijuana possession and sale arrest rate, run on all cities
print("Marijuana possession and sale arrest rate, all cities")
#regression_function_no_cluster("marijuana_possession_and_sale_arrest_rate", all_cities, "decriminilization_status_fraction_of_year_legalized_by_city")
regression_function_clustered("marijuana_possession_and_sale_arrest_rate", all_cities, "decriminilization_status_fraction_of_year_legalized_by_city")



#marijuana possession arrest rate disparity, run on all cities
print("Marijuana possession arrest rate disparity, all cities")
#regression_function_no_cluster("marijuana_possession_arrest_rate_disparity", all_cities, "decriminilization_status_fraction_of_year_legalized_by_city")
regression_function_clustered("marijuana_possession_arrest_rate_disparity", all_cities, "decriminilization_status_fraction_of_year_legalized_by_city")

#marijuana possession and sale arrest rate disparity, run on all cities
print("Marijuana possession and sale arrest rate disparity, all cities")
#regression_function_no_cluster("marijuana_possession_and_sale_arrest_rate_disparity", all_cities, "decriminilization_status_fraction_of_year_legalized_by_city")
regression_function_clustered("marijuana_possession_and_sale_arrest_rate_disparity", all_cities, "decriminilization_status_fraction_of_year_legalized_by_city")




#black marijuana posession arrest rate, run on all cities
print("Black marijuana posession arrest rate, run on all cities")
#regression_function_no_cluster("black_marijuana_possession_arrest_rate", all_cities, "decriminilization_status_fraction_of_year_legalized_by_city")
regression_function_clustered("black_marijuana_possession_arrest_rate", all_cities, "decriminilization_status_fraction_of_year_legalized_by_city")

#black marijuana posession and sale arrest rate, run on all cities
print("Black marijuana posession and sale arrest rate, run on allcities")
#regression_function_no_cluster("black_marijuana_possession_and_sale_arrest_rate", all_cities, "decriminilization_status_fraction_of_year_legalized_by_city")
regression_function_clustered("black_marijuana_possession_and_sale_arrest_rate", all_cities, "decriminilization_status_fraction_of_year_legalized_by_city")




#nondrug misdemeanor arrest rate, run on all cities
print("Nondrug misdemeanor arrest rate, run on all cities")
#regression_function_no_cluster("non_drug_misdemeanor_arrest_rate", all_cities, "decriminilization_status_fraction_of_year_legalized_by_city")
regression_function_clustered("non_drug_misdemeanor_arrest_rate", all_cities, "decriminilization_status_fraction_of_year_legalized_by_city")





#black nondrug  misdemeanor arrest rate, run on all cities
print("Black nondrug  misdemeanor arrest rate, run on all cities")
#regression_function_no_cluster("black_non_drug_misdemeanor_arrest_rate", all_cities, "decriminilization_status_fraction_of_year_legalized_by_city")
regression_function_clustered("black_non_drug_misdemeanor_arrest_rate", all_cities, "decriminilization_status_fraction_of_year_legalized_by_city")



#nondrug misdemeanor arrest rate disparity, run on all cities
print("Nondrug misdemeanor arrest rate disparity, run on all cities")
#regression_function_no_cluster("non_drug_misdemeanor_arrest_rate_disparity", all_cities, "decriminilization_status_fraction_of_year_legalized_by_city")
regression_function_clustered("non_drug_misdemeanor_arrest_rate_disparity", all_cities, "decriminilization_status_fraction_of_year_legalized_by_city")


#total arrest rate, run on all cities
print("Total arrest rate, run on all cities")
#regression_function_no_cluster("total_arrest_rate", all_cities, "decriminilization_status_fraction_of_year_legalized_by_city")
regression_function_clustered("total_arrest_rate", all_cities, "decriminilization_status_fraction_of_year_legalized_by_city")


#total arrest rate disparity, run on all cities
print("Total arrest rate disparity, run on all citiess")
#regression_function_no_cluster("total_arrest_rate_disparity", all_cities, "decriminilization_status_fraction_of_year_legalized_by_city")
regression_function_clustered("total_arrest_rate_disparity", all_cities, "decriminilization_status_fraction_of_year_legalized_by_city")

sink()
```

```{r descriptive graphs of changes in marijuana arrest rate}

#total arrest rates in cities that decriminalized by 2016
UCR_arrest_totals_and_rates_with_pop %>% 
  filter(City %in% cities_that_decriminalized_by_end_of_2016_vector) %>% 
  ggplot(aes(x = Year, )) +
  geom_line(aes(y = total_arrest_rate,
                group = City,
                color = factor(decriminilization_status_one_equals_any_legalization_in_year))) +
  facet_wrap(~State) +
  theme(legend.position = "bottom", axis.text.x = element_text(size = 6, angle = 45))

#total arrest rates in cities that did not decriminalize by 2016
UCR_arrest_totals_and_rates_with_pop %>% 
  filter(!City %in% cities_that_decriminalized_by_end_of_2016_vector) %>% 
  ggplot(aes(x = Year, )) +
  geom_line(aes(y = total_arrest_rate, group = City)) +
  facet_wrap(~State) +
  theme(legend.position = "bottom", axis.text.x = element_text(size = 6, angle = 45))

#marijuana possession arrest rates in cities that decriminalized by 2016
UCR_arrest_totals_and_rates_with_pop %>% 
  filter(City %in% cities_that_decriminalized_by_end_of_2016_vector) %>% 
  ggplot(aes(x = Year, )) +
  geom_line(aes(y = marijuana_possession_arrest_rate,
                group = City,
                color = factor(decriminilization_status_one_equals_any_legalization_in_year))) +
  facet_wrap(~State) +
  theme(legend.position = "bottom", axis.text.x = element_text(size = 6, angle = 45))



#marijuana possesion and sale arrest rates in cities that decriminalized by 2016
UCR_arrest_totals_and_rates_with_pop %>% 
  filter(City %in% cities_that_decriminalized_by_end_of_2016_vector) %>% 
  ggplot(aes(x = Year, )) +
  geom_line(aes(y = marijuana_possession_and_sale_arrest_rate,
                group = City,
                color = factor(decriminilization_status_one_equals_any_legalization_in_year))) +
  facet_wrap(~State) +
  theme(legend.position = "bottom", axis.text.x = element_text(size = 6, angle = 45))


#marijuana arrest rates in cities that did not decriminalize by 2016
UCR_arrest_totals_and_rates_with_pop %>% 
  filter(!City %in% cities_that_decriminalized_by_end_of_2016_vector) %>% 
  ggplot(aes(x = Year, )) +
  geom_line(aes(y = marijuana_possession_arrest_rate,
                group = City,
                color = factor(decriminilization_status_one_equals_any_legalization_in_year))) +
  facet_wrap(~State) +
  theme(legend.position = "bottom", axis.text.x = element_text(size = 6, angle = 45))

#nondrug misdemeanor arrest rates in cities that decriminalized by 2016
UCR_arrest_totals_and_rates_with_pop %>% 
  filter(City %in% cities_that_decriminalized_by_end_of_2016_vector) %>% 
  ggplot(aes(x = Year, )) +
  geom_line(aes(y = black_non_drug_misdemeanor_arrest_rate,
                group = City,
                color = factor(decriminilization_status_one_equals_any_legalization_in_year))) +
  facet_wrap(~State) +
  theme(legend.position = "bottom", axis.text.x = element_text(size = 6, angle = 45))

#nondrug misdemeanor arrest rates in cities that did not decriminalized by 2016
UCR_arrest_totals_and_rates_with_pop %>% 
  filter(!City %in% cities_that_decriminalized_by_end_of_2016_vector) %>% 
  ggplot(aes(x = Year, )) +
  geom_line(aes(y = non_drug_misdemeanor_arrest_rate,
                group = City,
                color = factor(decriminilization_status_one_equals_any_legalization_in_year))) +
  facet_wrap(~State) +
  theme(legend.position = "bottom", axis.text.x = element_text(size = 6, angle = 45))








```


```{r test estimatr regressions with clustering}

test_model2 <- UCR_arrest_totals_and_rates_with_pop %>% 
  lm_robust(log(marijuana_possession_arrest_rate) ~ decriminilization_status_fraction_of_year_legalized_by_city +
                                                       pct_black +
                                                       total_violent_arrest_rate +
                                                       pct_in_poverty +
                                                       log_total_pop,
          data = .,
          weights = unweighted_sample_count_of_popE,
          clusters = State,
          subset = ACS_city_name %in% common_support_cities,
          fixed_effects = ~ City + Year,
          se_type = "stata")

summary(test_model2)
100 * ((exp(coef(test_model2)["decriminilization_status_fraction_of_year_legalized_by_city"]))-1)


regression_function <- function(dependent_variable, common_support, policy_variable){
  df <- UCR_arrest_totals_and_rates_with_pop
  #outcome <- paste("log(", dependent_variable,")") #log version
  outcome <- dependent_variable
  controls <- c(policy_variable, "total_violent_arrest_rate",  "log_total_pop", "pct_black", "pct_in_poverty")
  f <- as.formula(
    paste(outcome, 
        paste(controls, collapse = " + "), 
        sep = " ~ "))
  eval(bquote(lm_robust(.(f),
        data = df,
        weights = unweighted_sample_count_of_popE,
        clusters = State,
        subset = ACS_city_name %in% common_support,
        fixed_effects = ~ City + Year,
        se_type = "stata")))
}

output <- regression_function("marijuana_possession_arrest_rate", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")

output2 <- regression_function("marijuana_possession_and_sale_arrest_rate", common_support_cities, "decriminilization_status_fraction_of_year_legalized_by_city")

tab_model(output)


tab_model(output,
          show.p = TRUE, p.style = "asterisk", show.obs = FALSE,
          terms = "decriminilization_status_fraction_of_year_legalized_by_city",
          title = "Decriminilization's Impact on Marijuana Possession Arrest Rate")

tab_model(output, output2,
          show.p = TRUE, p.style = "asterisk", show.obs = FALSE,
          terms = "decriminilization_status_fraction_of_year_legalized_by_city",
          title = "Decriminilization's Impact on Marijuana Arrest Rates")

```


```{r graphs to include in paper}
#marijuana possession and sale arrest rates in cities that decriminalized by end of 2016
UCR_arrest_totals_and_rates_with_pop %>% 
  filter(City %in% common_support_cities) %>% 
  filter(City %in% cities_that_decriminalized_by_end_of_2016_vector) %>% 
  ggplot(aes(x = Year, y = (1000* marijuana_possession_and_sale_arrest_rate))) +
  geom_line(aes(group = City,
                color = factor(decriminilization_status_one_equals_any_legalization_in_year_by_city)),
            size = .8) +
  facet_wrap(~State) +
  geom_text_repel(aes(label = ifelse(Year == max(Year) & State != "California", as.character(City), NA_character_)), size = 3) +
  scale_color_discrete(name = "Decriminalization status:", labels = c("Did not decriminalize", "Decriminalized by end of that year")) +
  ylab("Marijuana possession and sale rate, per 1,000 residents") + xlab("Year") + 
  labs(title = "Marijuana possession and sale arrest rates, 2009 - 2016",
       subtitle = "Only includes cities in common support region") +
  #theme_minimal() +
  theme(legend.position = "bottom", axis.text.x = element_text(size = 9, angle = 0),
        strip.text.x = element_text(size = 11))


#marijuana possession and sale arrest rates in cities that decriminalized by end of 2016
UCR_arrest_totals_and_rates_with_pop %>% 
  filter(City %in% common_support_cities) %>% 
  filter(City %in% cities_that_decriminalized_by_end_of_2016_vector) %>% 
  ggplot(aes(x = Year, y = (1000* marijuana_possession_and_sale_arrest_rate))) +
  geom_line(aes(group = City,
                color = factor(decriminilization_status_one_equals_any_legalization_in_year_by_city)),
            size = .8) +
  facet_wrap(~City) +
  scale_color_discrete(name = "Decriminalization status:", labels = c("Did not decriminalize", "Decriminalized by end of that year")) +
  ylab("Marijuana possession and sale rate, per 1,000 residents") + xlab("Year") + 
  labs(title = "Marijuana possession and sale arrest rates, 2009 - 2016",
       subtitle = "Only includes cities in common support region") +
  #theme_minimal() +
  theme(legend.position = "bottom", axis.text.x = element_text(size = 9, angle = 0),
        strip.text.x = element_text(size = 11))
```